/**
 * xui shadcn theme - MUI v9 restyled 1:1 to shadcn/ui defaults.
 * Self-contained: imports only from @mui/material and react.
 * Token source: apps/showcase/src/index.css generated by shadcn CLI
 * (style radix-nova, base color neutral, css variables).
 */
import { createTheme } from "@mui/material/styles"

// ---------------------------------------------------------------------------
// Module augmentation: shared semantic vocabulary (spec: every future theme
// fills these same slots).
// ---------------------------------------------------------------------------
declare module "@mui/material/styles" {
  interface Palette {
    muted: { main: string; contrastText: string }
    accent: { main: string; contrastText: string }
    popover: { main: string; contrastText: string }
    card: { main: string; contrastText: string }
    border: string
    input: string
    ring: string
  }
  interface PaletteOptions {
    muted?: { main: string; contrastText: string }
    accent?: { main: string; contrastText: string }
    popover?: { main: string; contrastText: string }
    card?: { main: string; contrastText: string }
    border?: string
    input?: string
    ring?: string
  }
}

declare module "@mui/material/Button" {
  interface ButtonPropsVariantOverrides {
    link: true
  }
}

// ---------------------------------------------------------------------------
// Design tokens - transcribed from shadcn ground truth. Generated file wins.
// ---------------------------------------------------------------------------
const light = {
  background: "oklch(1 0 0)", // shadcn: --background
  foreground: "oklch(0.145 0 0)", // shadcn: --foreground
  card: "oklch(1 0 0)", // shadcn: --card
  cardForeground: "oklch(0.145 0 0)", // shadcn: --card-foreground
  popover: "oklch(1 0 0)", // shadcn: --popover
  popoverForeground: "oklch(0.145 0 0)", // shadcn: --popover-foreground
  primary: "oklch(0.205 0 0)", // shadcn: --primary
  primaryForeground: "oklch(0.985 0 0)", // shadcn: --primary-foreground
  secondary: "oklch(0.97 0 0)", // shadcn: --secondary
  secondaryForeground: "oklch(0.205 0 0)", // shadcn: --secondary-foreground
  muted: "oklch(0.97 0 0)", // shadcn: --muted
  mutedForeground: "oklch(0.556 0 0)", // shadcn: --muted-foreground
  accent: "oklch(0.97 0 0)", // shadcn: --accent
  accentForeground: "oklch(0.205 0 0)", // shadcn: --accent-foreground
  destructive: "oklch(0.577 0.245 27.325)", // shadcn: --destructive
  border: "oklch(0.922 0 0)", // shadcn: --border
  input: "oklch(0.922 0 0)", // shadcn: --input
  ring: "oklch(0.708 0 0)", // shadcn: --ring
}

const dark = {
  background: "oklch(0.145 0 0)", // shadcn: .dark --background
  foreground: "oklch(0.985 0 0)", // shadcn: .dark --foreground
  card: "oklch(0.205 0 0)", // shadcn: .dark --card
  cardForeground: "oklch(0.985 0 0)", // shadcn: .dark --card-foreground
  popover: "oklch(0.205 0 0)", // shadcn: .dark --popover
  popoverForeground: "oklch(0.985 0 0)", // shadcn: .dark --popover-foreground
  primary: "oklch(0.922 0 0)", // shadcn: .dark --primary
  primaryForeground: "oklch(0.205 0 0)", // shadcn: .dark --primary-foreground
  secondary: "oklch(0.269 0 0)", // shadcn: .dark --secondary
  secondaryForeground: "oklch(0.985 0 0)", // shadcn: .dark --secondary-foreground
  muted: "oklch(0.269 0 0)", // shadcn: .dark --muted
  mutedForeground: "oklch(0.708 0 0)", // shadcn: .dark --muted-foreground
  accent: "oklch(0.269 0 0)", // shadcn: .dark --accent
  accentForeground: "oklch(0.985 0 0)", // shadcn: .dark --accent-foreground
  destructive: "oklch(0.704 0.191 22.216)", // shadcn: .dark --destructive
  border: "oklch(1 0 0 / 10%)", // shadcn: .dark --border
  input: "oklch(1 0 0 / 15%)", // shadcn: .dark --input
  ring: "oklch(0.556 0 0)", // shadcn: .dark --ring
}

// shadcn: --radius: 0.625rem (base token set here as shape.borderRadius).
// The derived per-component scale in apps/showcase/src/index.css is
// MULTIPLICATIVE off this base, not the older subtractive calc(radius - Npx):
//   --radius-sm: calc(var(--radius) * 0.6)
//   --radius-md: calc(var(--radius) * 0.8)
//   --radius-lg: var(--radius)          (1x, i.e. the base itself)
//   --radius-xl: calc(var(--radius) * 1.4)
// Later tasks deriving per-component radii from shape.borderRadius must
// multiply, not subtract.
const RADIUS = "0.625rem"

const FONT_SANS = '"Geist Variable", ui-sans-serif, system-ui, sans-serif'

// shadcn: tailwind shadow-xs
const SHADOW_XS = "0 1px 2px 0 rgb(0 0 0 / 0.05)"

// DEFERRED (resolved in Task 4, where the first real browser render makes the
// symptom observable): MUI's CSS-variables pipeline derives a companion
// "<slot>Channel" CSS var for every main-shaped palette entry (e.g.
// --mui-palette-primary-mainChannel), a bare "R G B" triplet used to
// alpha-blend overlays via rgba(var(--...Channel) / <alpha>). Deriving it calls
// decomposeColor(), which cannot parse oklch(), so MUI logs a dev warning and
// falls back to the raw oklch string for background.default, background.paper,
// divider, primary, and secondary (the other oklch slots fail silently). Our
// theme never consumes these channel overlays - every interaction state is
// overridden with shadcn's own color-mix(in oklab, ...) - so they are inert,
// but the warnings violate our pristine-console bar. MUI exposes an escape
// hatch: setColorChannel() skips derivation when a `<slot>Channel` field is
// already present, so supplying precomputed sRGB "R G B" strings (main stays
// oklch, via deterministic CSS Color 4 oklch->sRGB math) silences the warnings
// without changing any rendered color. Task 4 wires this once the browser
// console confirms which warnings actually fire.
function schemePalette(t: typeof light) {
  return {
    background: { default: t.background, paper: t.card },
    text: { primary: t.foreground, secondary: t.mutedForeground },
    // shadcn has one flat color per role (no separate tonal shades), so
    // light/dark are pinned to main. Without this, MUI's createPalette
    // auto-derives light/dark via lighten()/darken(), which call
    // decomposeColor() - and MUI's decomposeColor only understands
    // #nnn, #nnnnnn, rgb(), rgba(), hsl(), hsla(), color(), NOT oklch().
    // Leaving light/dark undefined here throws at createTheme() time:
    // "MUI: Unsupported `oklch(...)` color."
    primary: {
      main: t.primary,
      light: t.primary,
      dark: t.primary,
      contrastText: t.primaryForeground,
    },
    secondary: {
      main: t.secondary,
      light: t.secondary,
      dark: t.secondary,
      contrastText: t.secondaryForeground,
    },
    error: {
      main: t.destructive,
      light: t.destructive,
      dark: t.destructive,
      contrastText: "#ffffff",
    },
    divider: t.border,
    muted: { main: t.muted, contrastText: t.mutedForeground },
    accent: { main: t.accent, contrastText: t.accentForeground },
    popover: { main: t.popover, contrastText: t.popoverForeground },
    card: { main: t.card, contrastText: t.cardForeground },
    border: t.border,
    input: t.input,
    ring: t.ring,
  }
}

export const shadcnTheme = createTheme({
  cssVariables: {
    colorSchemeSelector: "class", // generates .light/.dark on <html>, same as shadcn
  },
  colorSchemes: {
    light: { palette: schemePalette(light) },
    dark: { palette: schemePalette(dark) },
  },
  shape: {
    borderRadius: RADIUS, // shadcn: --radius
  },
  typography: {
    fontFamily: FONT_SANS,
    button: {
      textTransform: "none",
      fontWeight: 500, // shadcn: font-medium
      fontSize: "0.875rem", // shadcn: text-sm
      lineHeight: "1.25rem",
      letterSpacing: "normal",
    },
  },
  components: {
    MuiButtonBase: {
      defaultProps: {
        disableRipple: true, // shadcn has no ripple
      },
    },
    // Per-component overrides are appended by later tasks, one banner each.
  },
})
