/**
 * xui shadcn theme - MUI v9 restyled 1:1 to shadcn/ui defaults.
 * Self-contained: imports only from @mui/material/styles (no relative imports).
 * Token source: apps/showcase/src/index.css generated by shadcn CLI
 * (style radix-nova, base color neutral, css variables).
 */
import { createTheme, type CssVarsTheme, type Theme } from "@mui/material/styles"
import { Check } from "lucide-react"
// createElement (not JSX) because this file is a plain .ts module - JSX syntax is only
// valid in .tsx files, and this file's name/extension is fixed by the constraint that only
// packages/xui/src/themes/shadcn.ts may change. "react" itself is not a new external
// dependency - it is already xui's peerDependency/devDependency, required transitively by
// every MUI component this theme already configures.
import { createElement } from "react"

// ---------------------------------------------------------------------------
// Module augmentation: shared semantic vocabulary (spec: every future theme
// fills these same slots).
// ---------------------------------------------------------------------------
declare module "@mui/material/styles" {
  // Native background/text slots don't ship *Channel fields (MUI only types
  // them on the vars-internal shape, not the public Palette/PaletteOptions),
  // so we add them here to match what setColorChannel() actually populates.
  interface TypeBackground {
    defaultChannel: string
    paperChannel: string
  }
  interface TypeText {
    primaryChannel: string
    secondaryChannel: string
  }
  interface Palette {
    muted: { main: string; mainChannel: string; contrastText: string }
    accent: { main: string; mainChannel: string; contrastText: string }
    popover: { main: string; mainChannel: string; contrastText: string }
    card: { main: string; mainChannel: string; contrastText: string }
    border: string
    input: string
    ring: string
    dividerChannel: string
  }
  interface PaletteOptions {
    muted?: { main: string; mainChannel?: string; contrastText: string }
    accent?: { main: string; mainChannel?: string; contrastText: string }
    popover?: { main: string; mainChannel?: string; contrastText: string }
    card?: { main: string; mainChannel?: string; contrastText: string }
    border?: string
    input?: string
    ring?: string
    dividerChannel?: string
  }
}

declare module "@mui/material/Button" {
  interface ButtonPropsVariantOverrides {
    link: true
  }
}

// ---------------------------------------------------------------------------
// Design tokens - transcribed from shadcn ground truth. Generated file wins.
// ---------------------------------------------------------------------------
const light = {
  background: "oklch(1 0 0)", // shadcn: --background
  foreground: "oklch(0.145 0 0)", // shadcn: --foreground
  card: "oklch(1 0 0)", // shadcn: --card
  cardForeground: "oklch(0.145 0 0)", // shadcn: --card-foreground
  popover: "oklch(1 0 0)", // shadcn: --popover
  popoverForeground: "oklch(0.145 0 0)", // shadcn: --popover-foreground
  primary: "oklch(0.205 0 0)", // shadcn: --primary
  primaryForeground: "oklch(0.985 0 0)", // shadcn: --primary-foreground
  secondary: "oklch(0.97 0 0)", // shadcn: --secondary
  secondaryForeground: "oklch(0.205 0 0)", // shadcn: --secondary-foreground
  muted: "oklch(0.97 0 0)", // shadcn: --muted
  mutedForeground: "oklch(0.556 0 0)", // shadcn: --muted-foreground
  accent: "oklch(0.97 0 0)", // shadcn: --accent
  accentForeground: "oklch(0.205 0 0)", // shadcn: --accent-foreground
  destructive: "oklch(0.577 0.245 27.325)", // shadcn: --destructive
  border: "oklch(0.922 0 0)", // shadcn: --border
  input: "oklch(0.922 0 0)", // shadcn: --input
  ring: "oklch(0.708 0 0)", // shadcn: --ring
}

const dark = {
  background: "oklch(0.145 0 0)", // shadcn: .dark --background
  foreground: "oklch(0.985 0 0)", // shadcn: .dark --foreground
  card: "oklch(0.205 0 0)", // shadcn: .dark --card
  cardForeground: "oklch(0.985 0 0)", // shadcn: .dark --card-foreground
  popover: "oklch(0.205 0 0)", // shadcn: .dark --popover
  popoverForeground: "oklch(0.985 0 0)", // shadcn: .dark --popover-foreground
  primary: "oklch(0.922 0 0)", // shadcn: .dark --primary
  primaryForeground: "oklch(0.205 0 0)", // shadcn: .dark --primary-foreground
  secondary: "oklch(0.269 0 0)", // shadcn: .dark --secondary
  secondaryForeground: "oklch(0.985 0 0)", // shadcn: .dark --secondary-foreground
  muted: "oklch(0.269 0 0)", // shadcn: .dark --muted
  mutedForeground: "oklch(0.708 0 0)", // shadcn: .dark --muted-foreground
  accent: "oklch(0.269 0 0)", // shadcn: .dark --accent
  accentForeground: "oklch(0.985 0 0)", // shadcn: .dark --accent-foreground
  destructive: "oklch(0.704 0.191 22.216)", // shadcn: .dark --destructive
  border: "oklch(1 0 0 / 10%)", // shadcn: .dark --border
  input: "oklch(1 0 0 / 15%)", // shadcn: .dark --input
  ring: "oklch(0.556 0 0)", // shadcn: .dark --ring
}

// shadcn: --radius: 0.625rem (base token set here as shape.borderRadius).
// The derived per-component scale in apps/showcase/src/index.css is
// MULTIPLICATIVE off this base, not the older subtractive calc(radius - Npx):
//   --radius-sm: calc(var(--radius) * 0.6)
//   --radius-md: calc(var(--radius) * 0.8)
//   --radius-lg: var(--radius)          (1x, i.e. the base itself)
//   --radius-xl: calc(var(--radius) * 1.4)
// Later tasks deriving per-component radii from shape.borderRadius must
// multiply, not subtract.
const RADIUS = "0.625rem"

const FONT_SANS = '"Geist Variable", ui-sans-serif, system-ui, sans-serif'

// shadcn: the installed Button (apps/showcase/src/components/ui/button.tsx,
// style "radix-nova") applies no shadow-xs - or any box-shadow - on any
// variant, state, or color scheme. Verified with getComputedStyle: boxShadow
// resolves to "none" everywhere except the focus-visible ring, which is a
// separate box-shadow layer (see MuiButton below), not this token. Kept as
// a named constant rather than a bare "none" literal so MuiButton's root
// reset stays self-documenting, and consumed there (not exported) since it
// is no longer a bare unused local once a component uses it.
const SHADOW_XS = "none"

// RESOLVED (Task 4): MUI's CSS-variables pipeline derives a companion
// "<slot>Channel" CSS var for every main-shaped palette entry (e.g.
// --mui-palette-primary-mainChannel), a bare "R G B" triplet used to
// alpha-blend overlays via rgba(var(--...Channel) / <alpha>). Deriving it calls
// decomposeColor(), which cannot parse oklch(), so MUI logs a dev warning and
// falls back to the raw oklch string for background.default, background.paper,
// and divider (and silently produces empty/invalid channel CSS for primary,
// secondary, and the other main-shaped oklch slots). Our theme never consumes
// these channel overlays - every interaction state is overridden with
// shadcn's own color-mix(in oklab, ...) - so they are inert, but the warnings
// violate our pristine-console bar and the invalid CSS is still wasteful. MUI
// exposes an escape hatch: setColorChannel()/setColor() skip derivation
// whenever a `<slot>Channel` field is already present next to the color, so
// we precompute it ourselves with deterministic CSS Color 4 / Ottosson
// oklch->sRGB math and hand it over. The `main`/color values themselves stay
// their original oklch strings, so rendered colors are unchanged - only the
// inert *Channel siblings become plain sRGB triplets.
function oklchToRgbTriplet(css: string): string {
  const match = css.match(/oklch\(\s*([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)/)
  if (!match) {
    throw new Error(`oklchToRgbTriplet: cannot parse "${css}"`)
  }
  const L = Number(match[1])
  const C = Number(match[2])
  const H = Number(match[3])

  const h = (H * Math.PI) / 180
  const a = C * Math.cos(h)
  const b = C * Math.sin(h)

  const l_ = L + 0.3963377774 * a + 0.2158037573 * b
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b
  const s_ = L - 0.0894841775 * a - 1.2914855480 * b

  const l = l_ ** 3
  const m = m_ ** 3
  const s = s_ ** 3

  const rLin = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
  const gLin = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
  const bLin = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s

  const gamma = (c: number) => (c <= 0.0031308 ? 12.92 * c : 1.055 * Math.pow(c, 1 / 2.4) - 0.055)
  const toByte = (linear: number) => Math.round(Math.min(1, Math.max(0, gamma(linear))) * 255)

  return `${toByte(rLin)} ${toByte(gLin)} ${toByte(bLin)}`
}

function schemePalette(t: typeof light) {
  return {
    background: {
      default: t.background,
      defaultChannel: oklchToRgbTriplet(t.background),
      paper: t.card,
      paperChannel: oklchToRgbTriplet(t.card),
    },
    text: {
      primary: t.foreground,
      primaryChannel: oklchToRgbTriplet(t.foreground),
      secondary: t.mutedForeground,
      secondaryChannel: oklchToRgbTriplet(t.mutedForeground),
    },
    // shadcn has one flat color per role (no separate tonal shades), so
    // light/dark are pinned to main. Without this, MUI's createPalette
    // auto-derives light/dark via lighten()/darken(), which call
    // decomposeColor() - and MUI's decomposeColor only understands
    // #nnn, #nnnnnn, rgb(), rgba(), hsl(), hsla(), color(), NOT oklch().
    // Leaving light/dark undefined here throws at createTheme() time:
    // "MUI: Unsupported `oklch(...)` color."
    primary: {
      main: t.primary,
      mainChannel: oklchToRgbTriplet(t.primary),
      light: t.primary,
      dark: t.primary,
      contrastText: t.primaryForeground,
    },
    secondary: {
      main: t.secondary,
      mainChannel: oklchToRgbTriplet(t.secondary),
      light: t.secondary,
      dark: t.secondary,
      contrastText: t.secondaryForeground,
    },
    error: {
      main: t.destructive,
      mainChannel: oklchToRgbTriplet(t.destructive),
      light: t.destructive,
      dark: t.destructive,
      contrastText: "#ffffff",
    },
    divider: t.border,
    dividerChannel: oklchToRgbTriplet(t.border),
    muted: {
      main: t.muted,
      mainChannel: oklchToRgbTriplet(t.muted),
      contrastText: t.mutedForeground,
    },
    accent: {
      main: t.accent,
      mainChannel: oklchToRgbTriplet(t.accent),
      contrastText: t.accentForeground,
    },
    popover: {
      main: t.popover,
      mainChannel: oklchToRgbTriplet(t.popover),
      contrastText: t.popoverForeground,
    },
    card: {
      main: t.card,
      mainChannel: oklchToRgbTriplet(t.card),
      contrastText: t.cardForeground,
    },
    border: t.border,
    input: t.input,
    ring: t.ring,
  }
}

// ---------------------------------------------------------------------------
// TextField box recipe - shared by MuiOutlinedInput, MuiFilledInput, and MuiInput below.
// This project's approved design flattens all three MUI TextField variants (outlined/
// filled/standard) to the SAME shadcn Input/Textarea box, so all three trace to the exact
// same input.tsx/textarea.tsx ground truth (see the "TextField" banner in `components`
// below for the full class-string citations and GOTCHAs). Extracted once here so the
// three components stay in lockstep instead of being re-derived three times.
// ---------------------------------------------------------------------------
// createTheme's cssVariables-flavored overload types styleOverrides callbacks' `theme`
// param as `Theme & CssVarsTheme` (vars required), not the plain (vars-optional) `Theme`
// export - matched here so these extracted helpers accept the same object the inline
// callbacks below receive.
type ThemeWithVars = Theme & CssVarsTheme

function textFieldBoxBase(theme: ThemeWithVars, ownerState: { multiline?: boolean }) {
  return {
    position: "relative" as const,
    boxSizing: "border-box" as const,
    borderRadius: RADIUS, // shadcn: rounded-lg
    border: `1px solid ${theme.vars.palette.input}`, // shadcn: border border-input
    backgroundColor: "transparent", // shadcn: bg-transparent
    // No backgroundClip override here, unlike MuiButton/MuiIconButton's "padding-box" (bg-clip-padding
    // IS a real class on button.tsx). input.tsx/textarea.tsx carry no bg-clip-padding class - this was
    // previously set to "padding-box" here too, invented by analogy to Button rather than read from
    // this component's own ground truth. Left at the CSS initial value (border-box), that mismatch was
    // invisible everywhere the border is opaque, but dark mode's border-input is translucent
    // (oklch(1 0 0 / 15%)): "padding-box" clips the box's own dark:bg-input/30 fill out from under the
    // border ring, so the ring composites against the page background instead of the box's own fill -
    // measured via pixel sampling of the parity harness's own screenshots (e2e/results/diffs): shadcn's
    // real border pixel painted rgb(56,56,56) (border-input/15% over the box's OWN fill, rgb 21),
    // while "padding-box" made the MUI twin's border paint rgb(47,47,47) (the same alpha over the page
    // background, rgb 10, with no box fill beneath it) - a ~1.6% pixel mismatch across every dark-mode
    // TextField pair, previously hidden by the pixelmatch threshold bug fixed above.
    padding: 0, // box's own padding lives on the input/textarea slot below (matches shadcn's single-element box)
    ...(ownerState.multiline
      ? {
          height: "auto",
          minHeight: "4rem", // shadcn textarea: min-h-16
          // Does NOT stretch the textarea's height to fill this box - its real effect is to
          // top-anchor the textarea instead of MUI's own InputBaseRoot default
          // (alignItems: 'center'), matching shadcn's plain top-anchored textarea.
          alignItems: "stretch" as const,
        }
      : {
          height: "2rem", // shadcn input: h-8 (unconditional on MUI's size prop - see Size scope above)
        }),
  }
}

function textFieldBoxStates(theme: ThemeWithVars, ownerState: { multiline?: boolean }) {
  return {
    "&.Mui-focused": {
      borderColor: theme.vars.palette.ring, // shadcn: focus-visible:border-ring
      boxShadow: `0 0 0 3px color-mix(in oklab, ${theme.vars.palette.ring} 50%, transparent)`, // shadcn: focus-visible:ring-3 ring-ring/50
      // MuiFilledInput's own base style sets `&.Mui-focused { backgroundColor: <FilledInput.bg> }`
      // at 2-class specificity (`.MuiFilledInput-root.Mui-focused`), which beats the plain
      // (1-class, unconditional) backgroundColor: "transparent" that textFieldBoxBase sets on
      // the root regardless of source order - the same specificity trap already solved for
      // MuiInput's formControl margin-top below. Measured with getComputedStyle: focused MUI
      // filled root rendered rgba(0, 0, 0, 0.06) against the shadcn twin's rgba(0, 0, 0, 0).
      // Restated here (shared by all three variants) at matching specificity; harmless for
      // Outlined/Standard, which own no internal `.Mui-focused` background rule of their own.
      backgroundColor: "transparent",
    },
    "&.Mui-error": {
      borderColor: theme.vars.palette.error.main, // shadcn: aria-invalid:border-destructive
      boxShadow: `0 0 0 3px color-mix(in oklab, ${theme.vars.palette.error.main} 20%, transparent)`, // shadcn: aria-invalid:ring-3 ring-destructive/20
    },
    "&.Mui-disabled": {
      opacity: 0.5, // shadcn: disabled:opacity-50
      cursor: "not-allowed" as const, // shadcn: disabled:cursor-not-allowed (both input and textarea)
      pointerEvents: ownerState.multiline ? undefined : ("none" as const), // shadcn input: disabled:pointer-events-none; textarea has no such class
      backgroundColor: `color-mix(in oklab, ${theme.vars.palette.input} 50%, transparent)`, // shadcn: disabled:bg-input/50
      // Restates the normal (ambient) text color so opacity alone does the dimming - see the
      // matching GOTCHA note on MuiOutlinedInput's root below for why this is needed (MUI's
      // own InputBaseRoot `&.Mui-disabled` rule otherwise wins with a hardcoded grey).
      color: theme.vars.palette.text.primary,
    },
    ...theme.applyStyles("dark", {
      backgroundColor: `color-mix(in oklab, ${theme.vars.palette.input} 30%, transparent)`, // shadcn: dark:bg-input/30
      "&.Mui-focused": {
        // Same trap as the light `.Mui-focused` override above, restated at dark-scheme
        // specificity: without this, MUI's own focused background (opaque in dark mode too)
        // would beat this block's own unconditional dark:bg-input/30 ambient tint.
        backgroundColor: `color-mix(in oklab, ${theme.vars.palette.input} 30%, transparent)`, // shadcn: dark:bg-input/30 (unchanged by focus)
      },
      "&.Mui-error": {
        borderColor: `color-mix(in oklab, ${theme.vars.palette.error.main} 50%, transparent)`, // shadcn: dark:aria-invalid:border-destructive/50
        boxShadow: `0 0 0 3px color-mix(in oklab, ${theme.vars.palette.error.main} 40%, transparent)`, // shadcn: dark:aria-invalid:ring-destructive/40
      },
      "&.Mui-disabled": {
        backgroundColor: `color-mix(in oklab, ${theme.vars.palette.input} 80%, transparent)`, // shadcn: dark:disabled:bg-input/80
      },
    }),
  }
}

function textFieldInputStyle(theme: ThemeWithVars, ownerState: { multiline?: boolean }) {
  return {
    boxSizing: "border-box" as const,
    height: "100%",
    fontFamily: "inherit",
    fontSize: "0.875rem", // shadcn: md:text-sm (harness viewport is 1440px, past the md breakpoint)
    // Tailwind's text-sm carries its own paired line-height (1.25rem). Without this, the
    // input inherits InputBaseRoot's own 1.4375em line-height computed at typography.body1's
    // 16px font-size (23px) rather than recomputing at this element's own 14px font-size.
    lineHeight: "1.25rem", // shadcn: text-sm's paired line-height
    color: "inherit",
    "&::placeholder": {
      color: theme.vars.palette.text.secondary, // shadcn: placeholder:text-muted-foreground
      opacity: 1,
    },
    "&::-webkit-input-placeholder": {
      color: theme.vars.palette.text.secondary,
      opacity: 1,
    },
    "&.Mui-disabled": {
      // InputBaseInput's own internal `&.Mui-disabled` rule sets -webkit-text-fill-color to
      // MUI's hardcoded text.disabled grey, which wins over `color` for the rendered glyph
      // fill regardless of the `color: inherit` above. shadcn dims disabled text via
      // opacity-50 alone, so this inherits the (now-corrected) ambient color instead.
      WebkitTextFillColor: "inherit",
    },
    ...(ownerState.multiline
      ? {
          padding: "0.5rem 0.625rem", // shadcn textarea: px-2.5 py-2
          // Ground truth (apps/showcase/src/components/ui/textarea.tsx) carries no
          // resize-none class, so the real shadcn textarea keeps its vertical-only resize
          // grip. That grip is NOT the browser's native default - a bare <textarea> resizes
          // both axes (`resize: both`) absent any CSS. It comes from Tailwind's own preflight
          // base styles (`textarea { resize: vertical }`), which the installed shadcn
          // textarea inherits as an unstyled base element.
          resize: "vertical" as const,
        }
      : {
          padding: "0.25rem 0.625rem", // shadcn input: px-2.5 py-1
        }),
  }
}

export const shadcnTheme = createTheme({
  cssVariables: {
    colorSchemeSelector: "class", // generates .light/.dark on <html>, same as shadcn
  },
  colorSchemes: {
    light: { palette: schemePalette(light) },
    dark: { palette: schemePalette(dark) },
  },
  shape: {
    borderRadius: RADIUS, // shadcn: --radius
  },
  typography: {
    fontFamily: FONT_SANS,
    button: {
      textTransform: "none",
      fontWeight: 500, // shadcn: font-medium
      fontSize: "0.875rem", // shadcn: text-sm
      lineHeight: "1.25rem",
      letterSpacing: "normal",
    },
  },
  components: {
    MuiButtonBase: {
      defaultProps: {
        disableRipple: true, // shadcn has no ripple
      },
    },
    // -----------------------------------------------------------------------
    // Button
    //
    // Ground truth: apps/showcase/src/components/ui/button.tsx (cva, style
    // "radix-nova"), read directly rather than assumed. Every value below was
    // cross-checked with getComputedStyle() on the live shadcn button (light
    // + dark, default/hover/focus-visible) - see task-7-report.md for the
    // full before/after table. The installed source has drifted from an
    // older/typical shadcn button in several load-bearing ways.
    //
    // base (all variants/sizes):
    //   group/button inline-flex shrink-0 items-center justify-center
    //   rounded-lg border border-transparent bg-clip-padding text-sm
    //   font-medium whitespace-nowrap transition-all outline-none select-none
    //   focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50
    //   active:not-aria-[haspopup]:translate-y-px disabled:pointer-events-none
    //   disabled:opacity-50 aria-invalid:* (no invalid/form-validated buttons
    //   in the gallery - out of scope) [&_svg]:pointer-events-none
    //   [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4
    //
    // variant (only what the gallery exercises: default/outline/secondary/
    // ghost/destructive/link; the icon/icon-*/xs sizes have no MUI `size`
    // equivalent and are unused - out of scope):
    //   default:     bg-primary text-primary-foreground hover:bg-primary/80
    //   outline:     border-border bg-background hover:bg-muted hover:text-foreground
    //                dark:border-input dark:bg-input/30 dark:hover:bg-input/50
    //   secondary:   bg-secondary text-secondary-foreground
    //                hover:bg-[color-mix(in_oklch,var(--secondary),var(--foreground)_5%)]
    //   ghost:       (no base bg/text class) hover:bg-muted hover:text-foreground
    //                dark:hover:bg-muted/50
    //   destructive: bg-destructive/10 text-destructive hover:bg-destructive/20
    //                focus-visible:border-destructive/40 focus-visible:ring-destructive/20
    //                dark:bg-destructive/20 dark:hover:bg-destructive/30
    //                dark:focus-visible:ring-destructive/40
    //   link:        text-primary underline-offset-4 hover:underline
    //
    // size (default/sm/lg only - mapped 1:1 to MUI medium/small/large):
    //   default: h-8 gap-1.5 px-2.5                      -> 32px / 6px / 0 10px
    //   sm:      h-7 gap-1 px-2.5 text-[0.8rem]
    //            rounded-[min(var(--radius-md),12px)]     -> 28px / 4px / 0 10px / 12.8px, 8px radius
    //            [&_svg:not([class*='size-'])]:size-3.5   -> 14px icons
    //   lg:      h-9 gap-1.5 px-2.5                       -> 36px / 6px / 0 10px (font/radius/gap = default)
    //
    // Corrections vs. the Task 7 plan's first-draft code (written against an
    // older shadcn registry; wrong on every point below):
    //   - radius is rounded-lg == var(--radius) == 10px, not rounded-md
    //     (8px); only the small size drops to radius-md (8px, via the
    //     multiplicative --radius-md: calc(var(--radius) * 0.8) scale - the
    //     "min(...,12px)" cap in the source is inert at this RADIUS value).
    //   - padding-inline is px-2.5 (10px) for EVERY size, not px-3/4/6;
    //     vertical padding is always 0 (height + flex centering only, no
    //     py-* class exists).
    //   - the default/primary hover tint is bg-primary/80, not /90.
    //   - destructive is NOT a solid red button with white text. It is
    //     bg-destructive/10 with text-destructive (a pale "soft" button),
    //     hover bg-destructive/20, and its OWN focus ring
    //     (border-destructive/40, ring-destructive/20, dark ring/40)
    //     instead of the shared ring token - this was the 18%+ mismatch.
    //   - outline/ghost hover use bg-muted + text-foreground, not bg-accent.
    //   - no shadow-xs (or any shadow) appears anywhere on the installed
    //     button; SHADOW_XS above has been corrected to "none" to match and
    //     is consumed here as an explicit reset.
    //   - cursor is the browser default (no cursor-pointer class), not
    //     pointer; MUI's ButtonBase defaults to cursor:pointer, so it is
    //     forced back to match.
    //   - MUI's built-in "text" and "outlined" variants colour their label
    //     with palette.primary.main (the `color` prop default) rather than
    //     the ambient foreground text - invisible in THIS theme's default
    //     light/dark grays because pixelmatch's anti-aliasing skip absorbs
    //     the difference on thin glyph strokes, but it is a real, measured
    //     mismatch (dark: 0.922 vs 0.985 OKLCH lightness) and is fixed
    //     explicitly below rather than left to that leniency.
    // -----------------------------------------------------------------------
    MuiButton: {
      defaultProps: {
        disableElevation: true, // shadcn buttons carry no elevation shadow
      },
      styleOverrides: {
        root: ({ theme }) => ({
          minWidth: 0,
          height: "2rem", // shadcn: h-8 (default/medium size)
          padding: "0 0.625rem", // shadcn: px-2.5, uniform across sizes; no py-* (height + centering only)
          gap: "0.375rem", // shadcn: gap-1.5
          borderRadius: RADIUS, // shadcn: rounded-lg -> --radius-lg = var(--radius), 1x
          border: "1px solid transparent", // shadcn: border border-transparent
          backgroundClip: "padding-box", // shadcn: bg-clip-padding
          boxSizing: "border-box",
          whiteSpace: "nowrap",
          boxShadow: SHADOW_XS, // shadcn: no shadow on any button state
          transition: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)", // shadcn: transition-all
          outline: "none",
          cursor: "default", // shadcn: no cursor-pointer class; browser default
          userSelect: "none", // shadcn: select-none
          "& svg": { width: "1rem", height: "1rem" }, // shadcn: [&_svg:not([class*='size-'])]:size-4
          "& .MuiButton-startIcon, & .MuiButton-endIcon": { margin: 0 }, // root gap does the spacing instead
          "&:focus-visible": {
            borderColor: theme.vars.palette.ring, // shadcn: focus-visible:border-ring
            boxShadow: `0 0 0 3px color-mix(in oklab, ${theme.vars.palette.ring} 50%, transparent)`, // shadcn: focus-visible:ring-ring/50 ring-3
          },
          "&.Mui-disabled": {
            opacity: 0.5, // shadcn: disabled:opacity-50 (MUI's own graying is undone per-variant below)
          },
        }),
      },
      variants: [
        {
          props: { variant: "contained", color: "primary" },
          style: ({ theme }) => ({
            backgroundColor: theme.vars.palette.primary.main, // shadcn: bg-primary
            color: theme.vars.palette.primary.contrastText, // shadcn: text-primary-foreground
            "&:hover": {
              backgroundColor: `color-mix(in oklab, ${theme.vars.palette.primary.main} 80%, transparent)`, // shadcn: hover:bg-primary/80
            },
            "&.Mui-disabled": {
              backgroundColor: theme.vars.palette.primary.main,
              color: theme.vars.palette.primary.contrastText,
            },
          }),
        },
        {
          props: { variant: "contained", color: "secondary" },
          style: ({ theme }) => ({
            backgroundColor: theme.vars.palette.secondary.main, // shadcn: bg-secondary
            color: theme.vars.palette.secondary.contrastText, // shadcn: text-secondary-foreground
            "&:hover": {
              // shadcn: hover:bg-[color-mix(in_oklch,var(--secondary),var(--foreground)_5%)]
              backgroundColor: `color-mix(in oklch, ${theme.vars.palette.secondary.main}, ${theme.vars.palette.text.primary} 5%)`,
            },
            "&.Mui-disabled": {
              backgroundColor: theme.vars.palette.secondary.main,
              color: theme.vars.palette.secondary.contrastText,
            },
          }),
        },
        {
          props: { variant: "contained", color: "error" },
          style: ({ theme }) => ({
            // shadcn destructive is a pale/soft button, not solid (see banner above)
            backgroundColor: `color-mix(in oklab, ${theme.vars.palette.error.main} 10%, transparent)`, // shadcn: bg-destructive/10
            color: theme.vars.palette.error.main, // shadcn: text-destructive
            "&:hover": {
              backgroundColor: `color-mix(in oklab, ${theme.vars.palette.error.main} 20%, transparent)`, // shadcn: hover:bg-destructive/20
            },
            "&:focus-visible": {
              borderColor: `color-mix(in oklab, ${theme.vars.palette.error.main} 40%, transparent)`, // shadcn: focus-visible:border-destructive/40
              boxShadow: `0 0 0 3px color-mix(in oklab, ${theme.vars.palette.error.main} 20%, transparent)`, // shadcn: focus-visible:ring-destructive/20
            },
            "&.Mui-disabled": {
              backgroundColor: `color-mix(in oklab, ${theme.vars.palette.error.main} 10%, transparent)`,
              color: theme.vars.palette.error.main,
            },
            ...theme.applyStyles("dark", {
              backgroundColor: `color-mix(in oklab, ${theme.vars.palette.error.main} 20%, transparent)`, // shadcn: dark:bg-destructive/20
              "&:hover": {
                backgroundColor: `color-mix(in oklab, ${theme.vars.palette.error.main} 30%, transparent)`, // shadcn: dark:hover:bg-destructive/30
              },
              "&:focus-visible": {
                boxShadow: `0 0 0 3px color-mix(in oklab, ${theme.vars.palette.error.main} 40%, transparent)`, // shadcn: dark:focus-visible:ring-destructive/40
              },
              "&.Mui-disabled": {
                backgroundColor: `color-mix(in oklab, ${theme.vars.palette.error.main} 20%, transparent)`,
              },
            }),
          }),
        },
        {
          props: { variant: "outlined" },
          style: ({ theme }) => ({
            border: `1px solid ${theme.vars.palette.border}`, // shadcn: border-border
            backgroundColor: theme.vars.palette.background.default, // shadcn: bg-background
            color: theme.vars.palette.text.primary, // shadcn: ambient foreground (MUI defaults outlined text to primary.main)
            "&:hover": {
              backgroundColor: theme.vars.palette.muted.main, // shadcn: hover:bg-muted
              color: theme.vars.palette.text.primary, // shadcn: hover:text-foreground
            },
            "&.Mui-disabled": {
              border: `1px solid ${theme.vars.palette.border}`,
              backgroundColor: theme.vars.palette.background.default,
              color: theme.vars.palette.text.primary,
            },
            ...theme.applyStyles("dark", {
              backgroundColor: `color-mix(in oklab, ${theme.vars.palette.input} 30%, transparent)`, // shadcn: dark:bg-input/30
              borderColor: theme.vars.palette.input, // shadcn: dark:border-input
              "&:hover": {
                backgroundColor: `color-mix(in oklab, ${theme.vars.palette.input} 50%, transparent)`, // shadcn: dark:hover:bg-input/50
              },
              // shadcn: dark:border-input wins the cascade over the base
              // focus-visible:border-ring in the installed app (Tailwind
              // orders the "dark:" variant after "focus-visible:", so the
              // dark border override is not itself overridden by focus) -
              // verified with getComputedStyle: dark+focused still reads
              // border-color from --input, not --ring. The ring box-shadow
              // is unaffected (nothing else contests that property) so only
              // border-color is restated here.
              "&:focus-visible": {
                borderColor: theme.vars.palette.input,
              },
              "&.Mui-disabled": {
                backgroundColor: `color-mix(in oklab, ${theme.vars.palette.input} 30%, transparent)`,
                borderColor: theme.vars.palette.input,
              },
            }),
          }),
        },
        {
          props: { variant: "text" },
          style: ({ theme }) => ({
            color: theme.vars.palette.text.primary, // shadcn ghost: ambient foreground (MUI defaults text variant to primary.main)
            "&:hover": {
              backgroundColor: theme.vars.palette.muted.main, // shadcn ghost: hover:bg-muted
              color: theme.vars.palette.text.primary, // shadcn ghost: hover:text-foreground
            },
            "&.Mui-disabled": {
              color: theme.vars.palette.text.primary,
            },
            ...theme.applyStyles("dark", {
              "&:hover": {
                backgroundColor: `color-mix(in oklab, ${theme.vars.palette.muted.main} 50%, transparent)`, // shadcn: dark:hover:bg-muted/50
              },
            }),
          }),
        },
        {
          props: { variant: "link" },
          style: ({ theme }) => ({
            color: theme.vars.palette.primary.main, // shadcn: text-primary
            textUnderlineOffset: "4px", // shadcn: underline-offset-4
            "&:hover": {
              textDecoration: "underline", // shadcn: hover:underline
              backgroundColor: "transparent",
            },
            "&.Mui-disabled": {
              color: theme.vars.palette.primary.main,
            },
          }),
        },
        {
          props: { size: "small" },
          style: {
            height: "1.75rem", // shadcn: h-7
            gap: "0.25rem", // shadcn: gap-1
            borderRadius: `calc(${RADIUS} * 0.8)`, // shadcn: rounded-[min(var(--radius-md),12px)] -> radius-md (12px cap inert here)
            fontSize: "0.8rem", // shadcn: text-[0.8rem]
            lineHeight: 1.5, // shadcn: arbitrary size has no paired line-height; inherits Tailwind preflight's html { line-height: 1.5 }
            "& svg": { width: "0.875rem", height: "0.875rem" }, // shadcn: [&_svg:not([class*='size-'])]:size-3.5
          },
        },
        {
          props: { size: "large" },
          style: {
            height: "2.25rem", // shadcn: h-9 (padding/gap/radius unchanged from default)
            // shadcn: text-sm (unchanged from default) - MUI's own sizeLarge default
            // asserts fontSize 15px (theme.typography.pxToRem(15)) that plain
            // inheritance from typography.button does not clear, so it is
            // restated explicitly here to hold at 14px.
            fontSize: "0.875rem",
          },
        },
      ],
    },
    // -----------------------------------------------------------------------
    // IconButton
    //
    // Ground truth: apps/showcase/src/components/ui/button.tsx (same cva as
    // Button above - shadcn ships no separate IconButton component; icon-only
    // buttons are just <Button size="icon"> or one of its icon-* size
    // variants). Mapped to MUI IconButton's small/medium/large sizes using
    // the shadcn "ghost" treatment (the conventional bare icon-button look -
    // no resting background, bg-muted on hover), since IconButton has no MUI
    // `variant` prop of its own to key off.
    //
    // shadcn icon size variants consumed (verbatim from the cva above,
    // mapped small/medium/large -> icon-sm/icon/icon-lg, mirroring how
    // MuiButton's size="small"/default/"large" already map to Button's
    // sm/default/lg 28/32/36px height ladder):
    //   icon:    size-8   -> 32px square; no radius override, so it falls
    //            through to the base rounded-lg == --radius-lg == RADIUS (10px)
    //   icon-sm: size-7 rounded-[min(var(--radius-md),12px)] -> 28px square,
    //            --radius-md = RADIUS * 0.8 = 8px (the 12px cap is inert at
    //            this RADIUS value - identical formula to MuiButton's
    //            size="small" radius above)
    //   icon-lg: size-9   -> 36px square; no radius override, same RADIUS as icon
    //   (icon-xs, size-6 with its own [&_svg:...]:size-3 override, has no MUI
    //   size equivalent - unused, out of scope, same as Button's xs size)
    // Unlike Button's text sizes, none of icon/icon-sm/icon-lg carries its
    // own svg-size override (only icon-xs does), so they all fall through to
    // the shared base [&_svg:not([class*='size-'])]:size-4 - svg sizing
    // (16px) is identical across all three mapped IconButton sizes.
    //
    // variant mapped (ghost only - the shadcn convention for bare icon
    // buttons; the gallery's four pairs only exercise default/hover/disabled
    // on this treatment):
    //   ghost: (no base bg/text class) hover:bg-muted hover:text-foreground
    //          dark:hover:bg-muted/50 - identical treatment (and identical
    //          correction away from a naive bg-accent guess) to MuiButton's
    //          "text" variant above.
    //
    // MUI IconButton ships its own padding (8/5/12px by size), a circular
    // (borderRadius: 50%) shape, a `color: action.active` default text
    // color, and a ripple-gated hover halo (--IconButton-hoverBg, itself
    // already inert here because MuiButtonBase.defaultProps sets
    // disableRipple: true globally above - see the `props =>
    // !props.disableRipple` gate in MUI's IconButton source). Padding,
    // radius, size, and color are reset explicitly below; the hover halo
    // needed no extra kill switch.
    // -----------------------------------------------------------------------
    MuiIconButton: {
      styleOverrides: {
        root: ({ theme }) => ({
          width: "2rem", // shadcn: size-8 (icon, default/medium)
          height: "2rem",
          padding: 0,
          borderRadius: RADIUS, // shadcn: rounded-lg -> --radius-lg = var(--radius), 1x
          border: "1px solid transparent", // shadcn: border border-transparent
          backgroundColor: "transparent", // shadcn ghost: no base bg class
          backgroundClip: "padding-box", // shadcn: bg-clip-padding
          boxSizing: "border-box",
          color: theme.vars.palette.text.primary, // shadcn ghost: ambient foreground (MUI defaults to action.active)
          fontSize: "0.875rem", // shadcn: text-sm (base class; icon sizes carry no font-size override) - MUI IconButton otherwise sets 24/18/28px by size
          boxShadow: SHADOW_XS, // shadcn: no shadow on any button state
          transition: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)", // shadcn: transition-all
          outline: "none",
          cursor: "default", // shadcn: no cursor-pointer class; browser default
          userSelect: "none", // shadcn: select-none
          "& svg": { width: "1rem", height: "1rem" }, // shadcn: [&_svg:not([class*='size-'])]:size-4
          "&:hover": {
            backgroundColor: theme.vars.palette.muted.main, // shadcn ghost: hover:bg-muted
            color: theme.vars.palette.text.primary, // shadcn ghost: hover:text-foreground
          },
          "&:focus-visible": {
            borderColor: theme.vars.palette.ring, // shadcn: focus-visible:border-ring
            boxShadow: `0 0 0 3px color-mix(in oklab, ${theme.vars.palette.ring} 50%, transparent)`, // shadcn: focus-visible:ring-ring/50 ring-3
          },
          "&.Mui-disabled": {
            opacity: 0.5, // shadcn: disabled:opacity-50 (MUI's own graying is undone below)
            color: theme.vars.palette.text.primary,
          },
          ...theme.applyStyles("dark", {
            "&:hover": {
              backgroundColor: `color-mix(in oklab, ${theme.vars.palette.muted.main} 50%, transparent)`, // shadcn: dark:hover:bg-muted/50
            },
          }),
        }),
      },
      variants: [
        {
          props: { size: "small" },
          style: {
            width: "1.75rem", // shadcn: icon-sm size-7
            height: "1.75rem",
            borderRadius: `calc(${RADIUS} * 0.8)`, // shadcn: rounded-[min(var(--radius-md),12px)] -> radius-md (12px cap inert here)
          },
        },
        {
          props: { size: "large" },
          style: {
            width: "2.25rem", // shadcn: icon-lg size-9
            height: "2.25rem",
            // radius/svg unchanged from default - icon-lg has no rounded/svg override
          },
        },
      ],
    },
    // -----------------------------------------------------------------------
    // TextField
    //
    // Ground truth: apps/showcase/src/components/ui/input.tsx, textarea.tsx,
    // label.tsx, read directly (class strings quoted below, each consumed
    // value tagged `// shadcn:`).
    //
    // Twin choice: field.tsx's Field/FieldLabel/FieldContent/FieldDescription
    // primitives were evaluated as the "fuller stack" twin the task brief
    // flagged as a possibility, but they are built for compound/grouped
    // fields (checkbox-group, radio-group, horizontal label+control rows) -
    // FieldContent's gap-0.5 tight stacking, FieldLabel's
    // has-[>[data-slot=field]] box styling, and FieldDescription's
    // nth-last-2/group-has-data-horizontal selectors all target that
    // composite use case, not a bare label-above-input. Nothing else in this
    // app composes Field/FieldLabel/FieldDescription together (no existing
    // convention to anchor on). label.tsx + input.tsx + textarea.tsx are
    // used directly instead. FieldError (also from field.tsx) IS reused
    // as-is for the one pair that needs helper text (textfield-error) - its
    // plain `text-sm font-normal text-destructive` is exactly a destructive
    // caption with no compound-field baggage, and input.tsx/textarea.tsx/
    // label.tsx define no helper-text look of their own.
    //
    // input.tsx: h-8 w-full min-w-0 rounded-lg border border-input
    //   bg-transparent px-2.5 py-1 text-base transition-colors outline-none
    //   placeholder:text-muted-foreground focus-visible:border-ring
    //   focus-visible:ring-3 focus-visible:ring-ring/50
    //   disabled:pointer-events-none disabled:cursor-not-allowed
    //   disabled:bg-input/50 disabled:opacity-50 aria-invalid:border-destructive
    //   aria-invalid:ring-3 aria-invalid:ring-destructive/20 md:text-sm
    //   dark:bg-input/30 dark:disabled:bg-input/80 dark:aria-invalid:border-destructive/50
    //   dark:aria-invalid:ring-destructive/40 (file:* omitted - no type="file"
    //   pair in the gallery, out of scope)
    // textarea.tsx: same recipe as input.tsx except min-h-16 (not h-8),
    //   px-2.5 py-2 (not py-1), and disabled:cursor-not-allowed WITHOUT
    //   disabled:pointer-events-none (input.tsx has both - textarea.tsx only
    //   has the cursor one, a real and easy-to-miss difference).
    // label.tsx: flex items-center gap-2 text-sm leading-none font-medium
    //   select-none (group-data-disabled/peer-disabled clauses don't fire in
    //   this composition - see GOTCHA below).
    // Viewport is 1440px (e2e/playwright.config.ts) - well past Tailwind's md
    // breakpoint, so md:text-sm (14px) is the effective input/textarea font
    // size, not the base text-base (16px).
    //
    // Label-to-control and control-to-helper spacing (8px) is this task's
    // own choice - none of the three files fix a container gap (that's
    // caller-owned in every real shadcn composition; the gallery's own
    // wrapper uses a plain flex column with an 8px gap). MuiFormControl (the
    // layout parent) has no `gap` of its own and is out of this task's
    // scope (shared with future components) - so the same 8px is
    // reconstructed here via InputLabel marginBottom / FormHelperText
    // marginTop instead.
    //
    // Flattening mechanism: MuiInputLabel.defaultProps sets shrink: true
    // (see GOTCHA below) and styleOverrides.root unconditionally overrides
    // position/transform. MuiFormControl is already `display:inline-flex;
    // flex-direction:column`, so a `position:static` label (no longer
    // absolutely positioned into the notch) naturally stacks above the
    // input in normal flow - no wrapper component needed. This unconditional
    // override is proven to beat the component's own internal conditional
    // variants (e.g. InputLabel's own formControl/shrink-conditional
    // position:absolute + transform) the same way MuiButton's root height
    // already beats MUI's internal sizeMedium variant: reading
    // @mui/system's createStyled.mjs, every styled() call resolves to
    // `expressions = [...expressionsHead, ...expressionsBody, ...expressionsTail]`
    // fed straight to emotion, where expressionsBody is the component's own
    // base style + internal `variants` array, and expressionsTail is
    // `[styleThemeOverrides, styleThemeVariants, styleFunctionSx]` - i.e.
    // our styleOverrides.root is always serialized after (and so wins CSS's
    // same-specificity source-order tiebreak over) the component's own
    // internal variants, and top-level theme `variants` win over both.
    //
    // GOTCHA - shrink must be true, not false: InputBaseInput's own source
    // hides the placeholder via the selector
    // `label[data-shrink=false] + .MuiInputBase-formControl &::-webkit-input-placeholder`
    // (opacity 0 unless focused - a leftover of "the placeholder only shows
    // once the label has floated out of the way"). That selector's
    // specificity (1 attribute + 2 classes + 1 pseudo-element) beats a plain
    // `&::placeholder` rule in styleOverrides.input regardless of source
    // order, so with shrink: false the placeholder would stay invisible at
    // rest on every field. Forcing shrink: true sidesteps the selector
    // entirely (it only matches data-shrink="false"); every other
    // shrink-conditional style (the scale/translate float transform) is
    // still fully overridden below regardless of which shrink value MUI
    // computes, per the unconditional-override mechanism above.
    //
    // GOTCHA - the label does not react to error/disabled in real shadcn:
    // shadcn's bare <Label> has no error-state styling, and its
    // `peer-disabled:opacity-50` only fires when the label is a LATER
    // sibling of the disabled peer (input-before-label, e.g. a checkbox
    // row) - with Label-before-Input (this composition, and the ordinary
    // form idiom) it never matches, so the label stays full-opacity/normal
    // color next to a disabled or invalid input. FormLabel's own internal
    // variants auto-color `&.Mui-error`/`&.Mui-disabled` (as a compound
    // class selector, beating a plain base color regardless of source
    // order) - both are explicitly neutralized below back to the ambient
    // foreground so the label stays inert exactly like the real shadcn
    // Label does.
    //
    // notchedOutline (the fieldset/legend "notch" the label used to float
    // into) is display:none entirely - the box is drawn on the
    // OutlinedInput root instead, which is only possible because the label
    // float/notch that the outline exists to accommodate is gone.
    //
    // Box construction: height/min-height + border + radius + background
    // live on the OutlinedInput root (the box shadcn draws on the single
    // <input>/<textarea> element itself); the actual <input>/<textarea> is
    // given width/height 100% with no border of its own so its native
    // text-vertical-centering (a real text-type form control, same element
    // type as shadcn's) resolves identically to shadcn's single-element box
    // at the same content-box dimensions.
    //
    // Focus ring mapping: the harness's "focus" state is always synthesized
    // via helper-button+keyboard-Tab (e2e/lib/states.ts:focusVisible), which
    // matches real :focus-visible on the shadcn side. MUI's InputBase marks
    // focus with a `.Mui-focused` class from a plain onFocus/onBlur handler
    // (any focus, not gated to keyboard) rather than a `:focus-visible`
    // pseudo-class - but since the harness never exercises "focus via mouse
    // click" as a distinct state, `.Mui-focused` is present at exactly the
    // moments `:focus-visible` would be on the shadcn side, so keying the
    // ring off `.Mui-focused` reproduces the same before/after screenshots.
    // `.Mui-error` is declared after `.Mui-focused` below (both are
    // single-class same-specificity selectors on the root) so an
    // errored+focused field keeps the destructive ring, matching Tailwind's
    // class order in input.tsx/textarea.tsx (aria-invalid: is written after
    // focus-visible:, so it wins the same tie in the real component too).
    //
    // Variant scope: this project's approved design deliberately flattens ALL THREE
    // MUI TextField variants (outlined/filled/standard) to the SAME shadcn Input/Textarea
    // box, so MuiOutlinedInput, MuiFilledInput, and MuiInput (standard) are all themed here
    // with the identical box recipe (textFieldBoxBase/textFieldBoxStates/textFieldInputStyle
    // above), each covered by its own gallery pair (textfield-basic/-filled/-standard).
    // MuiFilledInput and MuiInput additionally need their Material-specific underline
    // pseudo-elements (`&::before`/`&::after`, including the hover-thickening variant) and,
    // for MuiFilledInput, its own resting/hover/focused/disabled background tokens
    // neutralized - shadcn's input.tsx has no underline and no such background, and
    // notchedOutline: { display: "none" } below is the same idea applied to the outlined
    // variant's fieldset/legend notch.
    //
    // Size scope: shadcn's Input/Textarea each ship exactly one size (h-8 /
    // min-h-16 - no small/default/large ladder the way button.tsx has one).
    // The box below is intentionally unconditional on MUI's `size` prop
    // (see textfield-small pair) - MUI's own internal size="small" paddings
    // are overridden away the same way sizeMedium's height is in MuiButton.
    // -----------------------------------------------------------------------
    MuiInputLabel: {
      defaultProps: {
        shrink: true, // see GOTCHA above - sidesteps InputBaseInput's data-shrink=false placeholder-hiding selector
      },
      styleOverrides: {
        root: ({ theme }) => ({
          position: "static", // shadcn: Label sits in normal flow, not floating into the notch
          transform: "none", // kills the float/shrink translate+scale animation
          maxWidth: "100%",
          display: "flex", // shadcn: flex
          alignItems: "center", // shadcn: items-center
          gap: "0.5rem", // shadcn: gap-2
          marginBottom: "0.5rem", // label-to-control gap (this task's own choice, see banner)
          fontSize: "0.875rem", // shadcn: text-sm
          lineHeight: 1, // shadcn: leading-none
          fontWeight: 500, // shadcn: font-medium
          color: theme.vars.palette.text.primary, // shadcn: ambient foreground (Label sets no color class)
          userSelect: "none", // shadcn: select-none
          "&.Mui-focused": {
            color: theme.vars.palette.text.primary, // shadcn Label: no focus-state color change (MUI defaults to primary.main)
          },
          "&.Mui-error": {
            color: theme.vars.palette.text.primary, // shadcn Label: no error-state reaction (see GOTCHA above)
          },
          "&.Mui-disabled": {
            color: theme.vars.palette.text.primary, // shadcn Label: peer-disabled doesn't fire when Label precedes the control (see GOTCHA above)
          },
        }),
      },
    },
    MuiFormHelperText: {
      styleOverrides: {
        root: {
          marginTop: "0.5rem", // control-to-helper gap (this task's own choice, see banner)
          marginLeft: 0,
          marginRight: 0,
          fontSize: "0.875rem", // shadcn FieldError: text-sm
          // FieldError sets no explicit leading-* class, but Tailwind v4's text-sm utility
          // itself bundles a paired line-height (1.25rem), not the Preflight html{line-height:1.5}
          // fallback - measured via getComputedStyle: 20px, not 21px (1.5 * 14px).
          lineHeight: "1.25rem", // shadcn: text-sm's paired line-height
          fontWeight: 400, // shadcn FieldError: font-normal
          // .Mui-error intentionally untouched: MUI's own default already
          // colors it theme.vars.palette.error.main === destructive,
          // matching shadcn's FieldError text-destructive for free. The
          // non-error color is likewise left at MUI's own text.secondary
          // default - no gallery pair exercises a non-error helper text.
        },
      },
    },
    MuiOutlinedInput: {
      styleOverrides: {
        notchedOutline: {
          display: "none", // shadcn has no notch/legend - the box border is drawn on root instead
        },
        root: ({ theme, ownerState }) => ({
          ...textFieldBoxBase(theme, ownerState),
          ...textFieldBoxStates(theme, ownerState),
        }),
        input: ({ theme, ownerState }) => textFieldInputStyle(theme, ownerState),
      },
    },
    // -----------------------------------------------------------------------
    // TextField - filled variant
    //
    // Same shadcn Input/Textarea box as MuiOutlinedInput above (textFieldBoxBase/States/
    // textFieldInputStyle, all shared - see "Variant scope" banner above and the module-
    // level functions near the top of this file). On top of that box, FilledInput's own
    // Material-specific chrome is neutralized:
    //   - the underline pseudo-elements (`&::before`/`&::after`, plus the
    //     `&:hover:not(.Mui-disabled, .Mui-error):before` thickening variant MUI's source
    //     applies on hover) - shadcn's input.tsx draws no underline, only the box border
    //     already handled by textFieldBoxBase/States.
    //   - the resting/hover/focused/disabled background tints FilledInputRoot's own base
    //     style applies via theme.vars.palette.FilledInput.{bg,hoverBg,disabledBg} - shadcn's
    //     box is bg-transparent (dark:bg-input/30) exactly like the outlined box, already
    //     supplied by textFieldBoxBase/States, so every MUI-owned background state is reset
    //     back to transparent (states) here instead.
    // Both neutralizations rely on the same mechanism already proven for notchedOutline
    // above: styleOverrides is serialized after the component's own base style + internal
    // variants, so same-selector, same-specificity declarations here win the source-order
    // tiebreak (see the "Flattening mechanism" banner above for the full citation).
    // -----------------------------------------------------------------------
    MuiFilledInput: {
      styleOverrides: {
        root: ({ theme, ownerState }) => ({
          ...textFieldBoxBase(theme, ownerState),
          "&::before": {
            borderBottom: "none", // shadcn: input.tsx has no underline
          },
          "&::after": {
            borderBottom: "none", // shadcn: input.tsx has no underline
          },
          "&:hover:not(.Mui-disabled, .Mui-error):before": {
            borderBottom: "none", // shadcn: input.tsx has no hover state at all
          },
          "&:hover": {
            backgroundColor: "transparent", // shadcn: input.tsx has no hover class (FilledInput's own hoverBg neutralized)
          },
          ...textFieldBoxStates(theme, ownerState),
        }),
        input: ({ theme, ownerState }) => textFieldInputStyle(theme, ownerState),
      },
    },
    // -----------------------------------------------------------------------
    // TextField - standard variant
    //
    // Same shadcn Input/Textarea box as MuiOutlinedInput/MuiFilledInput above. MuiInput
    // (the "standard" variant) has no background chrome of its own to neutralize (unlike
    // FilledInput), only the underline pseudo-elements - same treatment as MuiFilledInput
    // above, citations there.
    //
    // GOTCHA - InputRoot's own internal `formControl` variant adds `margin-top: 16px` via
    // the compound selector `label + &, .MuiInputLabel-root + &` (reserving room for the
    // label that used to float down INTO the input in real Material Design's standard
    // variant). That selector's specificity (2 classes) beats a plain `&`-only rule
    // regardless of source order, so restating a bare `marginTop: 0` at the top level of
    // this override does NOT win - measured via getComputedStyle: 16px margin-top persisted
    // (a ~16px vertical offset against the shadcn twin) until the SAME compound selector was
    // restated below to reclaim equal specificity. shadcn's Label+Input stack has no such
    // reserved gap (MuiInputLabel above already accounts for the label-to-control spacing
    // via its own marginBottom).
    // -----------------------------------------------------------------------
    MuiInput: {
      styleOverrides: {
        root: ({ theme, ownerState }) => ({
          ...textFieldBoxBase(theme, ownerState),
          "label + &, .MuiInputLabel-root + &": {
            marginTop: 0, // see GOTCHA above
          },
          "&::before": {
            borderBottom: "none", // shadcn: input.tsx has no underline
          },
          "&::after": {
            borderBottom: "none", // shadcn: input.tsx has no underline
          },
          "&:hover:not(.Mui-disabled, .Mui-error):before": {
            borderBottom: "none", // shadcn: input.tsx has no hover state at all
          },
          ...textFieldBoxStates(theme, ownerState),
        }),
        input: ({ theme, ownerState }) => textFieldInputStyle(theme, ownerState),
      },
    },
    // -----------------------------------------------------------------------
    // Checkbox
    //
    // Ground truth: apps/showcase/src/components/ui/checkbox.tsx (radix-ui
    // Checkbox.Root/Indicator, style "radix-nova"), read directly and
    // cross-checked with getComputedStyle() on the live shadcn checkbox
    // (light + dark; unchecked/checked/indeterminate/disabled;
    // hover/focus-visible on unchecked+checked) via the Playwright MCP.
    //
    // checkbox.tsx root classes (CheckboxPrimitive.Root, verbatim):
    //   peer relative flex size-4 shrink-0 items-center justify-center
    //   rounded-[4px] border border-input transition-colors outline-none
    //   group-has-disabled/field:opacity-50 after:absolute after:-inset-x-3
    //   after:-inset-y-2 focus-visible:border-ring focus-visible:ring-3
    //   focus-visible:ring-ring/50 disabled:cursor-not-allowed
    //   disabled:opacity-50 aria-invalid:border-destructive
    //   aria-invalid:ring-3 aria-invalid:ring-destructive/20
    //   aria-invalid:aria-checked:border-primary dark:bg-input/30
    //   dark:aria-invalid:border-destructive/50
    //   dark:aria-invalid:ring-destructive/40 data-checked:border-primary
    //   data-checked:bg-primary data-checked:text-primary-foreground
    //   dark:data-checked:bg-primary
    // checkbox.tsx indicator classes (CheckboxPrimitive.Indicator, verbatim):
    //   grid place-content-center text-current transition-none
    //   [&>svg]:size-3.5, wrapping a lucide CheckIcon with no size/props of
    //   its own (no separate Minus/indeterminate glyph - see GOTCHA below).
    // No aria-invalid pair exists in this gallery (no invalid/error checkbox
    // state exercised) - the aria-invalid:* classes above are out of scope,
    // same convention as MuiButton's aria-invalid omission above.
    //
    // Extracted class -> CSS:
    //   size-4                    -> width/height: 1rem (16px)
    //   shrink-0 flex items-center justify-center -> display:flex, centered
    //   rounded-[4px]             -> borderRadius: 4px (a flat literal, NOT
    //                                derived from the --radius multiplicative
    //                                scale used elsewhere in this theme -
    //                                confirmed by the literal arbitrary-value
    //                                class, not a rounded-sm/md/lg token)
    //   border border-input       -> border: 1px solid var(--input)
    //   transition-colors         -> color/background-color/border-color
    //                                transition (150ms, Tailwind's default
    //                                easing - matches SHADOW_XS/MuiButton's
    //                                own transition timing already used
    //                                above)
    //   outline-none              -> outline: none
    //   dark:bg-input/30          -> dark-only fill; light has NO background
    //                                class at all (confirmed via
    //                                getComputedStyle: light rest state
    //                                backgroundColor is fully transparent,
    //                                "rgba(0, 0, 0, 0)", not a themed token)
    //   focus-visible:border-ring focus-visible:ring-3
    //   focus-visible:ring-ring/50
    //                             -> borderColor: ring, boxShadow: 0 0 0 3px
    //                                ring/50 (measured post-transition:
    //                                border reads exactly oklch(0.708 0 0)
    //                                (light ring) with no intermediate
    //                                blend - see focus GOTCHA below for why
    //                                an early read looked wrong)
    //   disabled:cursor-not-allowed disabled:opacity-50
    //                             -> opacity: 0.5, cursor: not-allowed
    //                                (checkbox.tsx has NO disabled:bg-*
    //                                class, unlike input.tsx/textarea.tsx -
    //                                disabled dims the ambient box via
    //                                opacity alone; confirmed no separate
    //                                disabled background color)
    //   data-checked:border-primary data-checked:bg-primary
    //   data-checked:text-primary-foreground
    //                             -> checked-only: borderColor: primary,
    //                                backgroundColor: primary, color:
    //                                primary.contrastText. "data-checked" is
    //                                a project-defined custom Tailwind
    //                                variant (confirmed by reading the
    //                                compiled stylesheet directly:
    //                                `&:where([data-state="checked"]),
    //                                &:where([data-checked]:not([data-checked
    //                                ="false"]))`) - it matches ONLY
    //                                data-state="checked", not "indeterminate"
    //                                or "unchecked". See indeterminate GOTCHA
    //                                below - this is the reason indeterminate
    //                                does NOT get the primary treatment.
    //   dark:data-checked:bg-primary
    //                             -> re-asserts checked's primary background
    //                                over dark:bg-input/30's unconditional
    //                                fill - the same "later/nested variant
    //                                must re-win over an unconditional dark
    //                                utility" trap already solved for
    //                                MuiFilledInput/MuiOutlinedInput above,
    //                                except this one IS present verbatim in
    //                                checkbox.tsx's own class list (not
    //                                invented by analogy).
    //   [&>svg]:size-3.5          -> checked/indeterminate icon: 0.875rem
    //                                (14px), centered in the 16px box
    //                                (measured: computed svg width/height
    //                                both exactly 14px)
    //
    // GOTCHA - indeterminate renders the SAME CheckIcon, un-tinted: radix's
    // CheckboxIndicator mounts (Presence) whenever forceMount || indeterminate
    // || checked === true - checkbox.tsx's Indicator has exactly one child,
    // <CheckIcon />, with NO conditional swap to a Minus/dash glyph for the
    // indeterminate data-state. The task brief's "swap for lucide Check/Minus"
    // guess was WRONG for this installed version - ground truth wins: only
    // Check is ever rendered, confirmed by inspecting the live indeterminate
    // pair's outerHTML (`<svg class="lucide lucide-check">`). Furthermore,
    // because "data-checked" (see above) matches data-state="checked" only,
    // an indeterminate checkbox gets ZERO of the primary/bg/border/text
    // treatment - it renders as a plain ambient (unchecked-looking) box that
    // merely happens to show a checkmark glyph in the ambient foreground
    // color instead of no glyph at all. Measured directly: indeterminate's
    // border/background/color are pixel-identical to the unchecked pair's,
    // both light and dark. This looks like an upstream quirk, not the
    // idealized "indeterminate = filled with a dash" pattern, but the task's
    // own rule is ground truth over invented-by-analogy assumptions, so it
    // is reproduced exactly: MuiCheckbox's `indeterminate` prop only swaps
    // the icon (via indeterminateIcon default prop below); it does NOT gate
    // any color/background style. This falls out for free from MUI's own
    // Checkbox implementation - when `indeterminate` is true and the
    // (uncontrolled) internal `checked` is false, MUI's SwitchBase renders
    // the `indeterminateIcon` prop WITHOUT adding the `Mui-checked` class, so
    // none of this override's `&.Mui-checked` rules fire - confirmed by
    // reading @mui/material's Checkbox.js: both the icon and checkedIcon
    // forwarded to SwitchBase resolve to `indeterminateIconProp` whenever
    // `indeterminate` is true, so SwitchBase's `checked ? checkedIcon : icon`
    // branch shows the same swapped icon regardless of the underlying
    // (uncontrolled, false) checked boolean.
    //
    // GOTCHA - focus ring must key off `.Mui-focusVisible`, not
    // `.Mui-focused` (unlike MuiOutlinedInput/MuiFilledInput/MuiInput above):
    // Checkbox is a SwitchBase/ButtonBase-family component, not an
    // InputBase-family one. SwitchBase renders an absolutely-positioned,
    // opacity:0 native `<input type="checkbox">` (zIndex 1, covering the
    // full root) as the ACTUAL focusable/hoverable element - the outer
    // `span.MuiCheckbox-root` itself has `tabIndex: null` and is never
    // directly focused. Reading @mui/material's ButtonBase.js: its
    // `handleFocus` checks `isFocusVisible(event.target)` (not
    // `event.currentTarget`) - since React's onFocus delegates via the
    // bubbling `focusin` event, `event.target` is the real focused element
    // (the nested input) even though the handler is attached to the outer
    // span. This sets ButtonBase's internal `focusVisible` state to true and
    // adds the global `Mui-focusVisible` class to the OUTER span - so the
    // ring can be themed on the root via a plain class selector exactly like
    // `:focus-visible` would look, without ever matching a literal
    // `&:focus-visible` selector (which would never fire, since the span
    // itself is never the focused DOM node). Confirmed empirically: focusing
    // the internal input and reading `.Mui-focusVisible` presence + the
    // ring's resolved border/box-shadow after the 150ms color transition
    // settles (an early read at 50ms showed a mid-transition blended color,
    // not a real mismatch - see harness's own 300ms settle wait in
    // e2e/lib/states.ts, which is long enough).
    //
    // `data-target` is placed on the internal `<input>` via
    // `slotProps={{ input: { "data-target": true } }}` (not the outer span) -
    // the input is the topmost element at the box's screen position (it
    // covers the full root, zIndex 1) so `.hover()` on it also satisfies the
    // outer root's own `&:hover` CSS (a hovered descendant keeps its
    // ancestors `:hover`-matched), and it is the only element that can
    // receive real keyboard focus for the harness's Tab-based
    // `focusVisible()` helper.
    //
    // No `&:hover` rule exists anywhere in this override: checkbox.tsx's
    // class list carries no "hover:" variant at all (confirmed both by
    // reading the class string and by getComputedStyle on a real
    // mouseover - border/background/color are byte-identical to the resting
    // state). MUI's own hover halo (SwitchBaseRoot/CheckboxRoot's internal
    // `disableRipple: false`-gated `&:hover` variants) is already inert
    // globally via `MuiButtonBase.defaultProps.disableRipple: true` set
    // above (SwitchBase renders a real `<ButtonBase>` under the hood, so the
    // same global default reaches it) - verified with getComputedStyle: no
    // hover halo paints on the themed MUI twin.
    //
    // GOTCHA - MUI's own internal `variants` (Checkbox.js, `props: {color:
    // 'primary'}` - the component's own default color) set
    // `&.Mui-checked, &.MuiCheckbox-indeterminate { color: primary.main }`
    // and `&.Mui-disabled { color: action.disabled }` UNCONDITIONALLY
    // whenever `color="primary"` (MUI Checkbox's own default, never
    // overridden by this gallery). Left alone, these would tint the
    // indeterminate icon primary-blue-grey and the disabled icon
    // MUI's own grey - both wrong per ground truth (indeterminate: ambient
    // foreground; disabled: ambient foreground dimmed by opacity alone).
    // Both are explicitly neutralized below (`&.MuiCheckbox-indeterminate`
    // and `&.Mui-disabled` re-asserting `color: text.primary`) - the same
    // "component's own internal variants lose to this styleOverrides.root
    // by source order" mechanism already proven for MuiButton/MuiTextField
    // above (styleOverrides is always serialized after the component's own
    // base style + internal variants).
    // -----------------------------------------------------------------------
    MuiCheckbox: {
      defaultProps: {
        // GOTCHA (found via a REAL Playwright mouse hover, not a synthetic dispatchEvent -
        // the latter doesn't engage actual :hover matching and silently hid this): the global
        // `MuiButtonBase.defaultProps.disableRipple: true` set above does NOT reach Checkbox.
        // @mui/material's Checkbox.js destructures its OWN `disableRipple = false` default
        // (via `useDefaultProps({..., name: 'MuiCheckbox'})`, not 'MuiButtonBase') and then
        // explicitly forwards that resolved (always-defined, never-undefined) value as a real
        // prop down through SwitchBase to the underlying ButtonBase - an explicit prop always
        // beats ButtonBase's own theme-default lookup (`useDefaultProps` only fills in
        // `undefined`s), so ButtonBase never sees the global MuiButtonBase default at all.
        // Concretely, without this: CheckboxRoot's own internal `variants` (gated on
        // `ownerState.disableRipple === false`, which it always was) applied a translucent
        // hover-halo `&:hover` background AND ButtonBase's focus-ripple pulse animation both
        // fired - confirmed by comparing e2e/results/diffs screenshots (a solid grey fill
        // inside the unchecked box on both hover and focus that shadcn's real twin, which has
        // no hover state and only a border+ring on focus, never shows). Restated here
        // per-component to actually reach Checkbox's own ownerState.
        disableRipple: true,
        // shadcn: checkbox.tsx's Indicator always renders the same lucide
        // CheckIcon for both "checked" and "indeterminate" data-states (see
        // GOTCHA above) - `icon` (rendered while neither checked nor
        // indeterminate) is the same glyph made invisible via `visibility:
        // hidden` rather than omitted, since MUI's SwitchBase always renders
        // one of `icon`/`checkedIcon` and Checkbox.js's `React.cloneElement`
        // call requires a valid element (a bare `null` throws). An invisible
        // element paints zero pixels, so this is visually identical to
        // shadcn's real DOM (which renders no indicator at all when
        // unchecked).
        icon: createElement(Check, { "aria-hidden": true, style: { visibility: "hidden" } }),
        checkedIcon: createElement(Check, { "aria-hidden": true }),
        indeterminateIcon: createElement(Check, { "aria-hidden": true }), // shadcn: same CheckIcon, not a Minus - see GOTCHA above
      },
      styleOverrides: {
        root: ({ theme }) => ({
          width: "1rem", // shadcn: size-4
          height: "1rem",
          padding: 0, // shadcn: no padding class (kills SwitchBaseRoot's own 9px base padding)
          boxSizing: "border-box",
          display: "flex", // shadcn: flex
          alignItems: "center", // shadcn: items-center
          justifyContent: "center", // shadcn: justify-center
          flexShrink: 0, // shadcn: shrink-0
          borderRadius: "4px", // shadcn: rounded-[4px] (flat literal, not the --radius scale)
          border: `1px solid ${theme.vars.palette.input}`, // shadcn: border border-input
          backgroundColor: "transparent", // shadcn: no base bg class (light)
          backgroundClip: "border-box", // shadcn: no bg-clip-padding class (unlike Button/IconButton) - left at CSS initial
          color: theme.vars.palette.text.primary, // shadcn: ambient foreground (CheckboxRoot's own base sets text.secondary - corrected here)
          outline: "none", // shadcn: outline-none
          cursor: "default", // shadcn: no cursor-pointer class; browser default (ButtonBase defaults to pointer)
          transition:
            "color 150ms cubic-bezier(0.4, 0, 0.2, 1), background-color 150ms cubic-bezier(0.4, 0, 0.2, 1), border-color 150ms cubic-bezier(0.4, 0, 0.2, 1)", // shadcn: transition-colors
          "& svg": { width: "0.875rem", height: "0.875rem" }, // shadcn: [&>svg]:size-3.5 (14px)
          "&.Mui-checked": {
            borderColor: theme.vars.palette.primary.main, // shadcn: data-checked:border-primary
            backgroundColor: theme.vars.palette.primary.main, // shadcn: data-checked:bg-primary
            color: theme.vars.palette.primary.contrastText, // shadcn: data-checked:text-primary-foreground
          },
          "&.MuiCheckbox-indeterminate": {
            color: theme.vars.palette.text.primary, // shadcn: indeterminate stays ambient (see GOTCHA above) - neutralizes MUI's own color:'primary' variant
          },
          "&.Mui-disabled": {
            opacity: 0.5, // shadcn: disabled:opacity-50
            cursor: "not-allowed", // shadcn: disabled:cursor-not-allowed
            color: theme.vars.palette.text.primary, // shadcn: no disabled color change - neutralizes MUI's own action.disabled tint
          },
          "&.Mui-focusVisible": {
            borderColor: theme.vars.palette.ring, // shadcn: focus-visible:border-ring
            boxShadow: `0 0 0 3px color-mix(in oklab, ${theme.vars.palette.ring} 50%, transparent)`, // shadcn: focus-visible:ring-3 ring-ring/50
          },
          ...theme.applyStyles("dark", {
            backgroundColor: `color-mix(in oklab, ${theme.vars.palette.input} 30%, transparent)`, // shadcn: dark:bg-input/30
            "&.Mui-checked": {
              backgroundColor: theme.vars.palette.primary.main, // shadcn: dark:data-checked:bg-primary (re-assert over dark:bg-input/30)
            },
          }),
        }),
      },
    },
    // -----------------------------------------------------------------------
    // Checkbox - with-label pairing
    //
    // Ground truth for the control+label row spacing: neither checkbox.tsx
    // nor label.tsx fixes a container gap (caller-owned, same situation as
    // MuiInputLabel's label-to-control gap above). No shadcn demo file is
    // installed in this app to anchor the exact spacing convention, so this
    // reuses the one real number already extracted from an installed file
    // for this exact "control + label, horizontal" composition:
    // apps/showcase/src/components/ui/field.tsx's `fieldVariants` base class
    // is `group/field flex w-full gap-2` (0.5rem, 8px) - Field's horizontal
    // orientation variant changes flex-direction but not this base gap. This
    // is this task's own choice for the *spacing value*, grounded in that
    // real file rather than invented from scratch or copied from a different
    // component's own hard-coded gap.
    //
    // FormControlLabelRoot's own base style (marginLeft: -11, marginRight:
    // 16, no gap) is neutralized to margin 0 + gap 8px; MuiFormControlLabel's
    // label Typography defaults to variant body1 (1rem/1.5/400) and is reset
    // to match label.tsx's own classes (text-sm leading-none font-medium,
    // ambient foreground - label.tsx carries no color class of its own).
    // -----------------------------------------------------------------------
    MuiFormControlLabel: {
      styleOverrides: {
        root: {
          marginLeft: 0,
          marginRight: 0,
          gap: "0.5rem", // this task's own choice, grounded in field.tsx's own gap-2 - see banner above
          cursor: "default", // shadcn: the control+label row carries no cursor-pointer class
        },
        label: ({ theme }) => ({
          fontSize: "0.875rem", // shadcn label.tsx: text-sm
          lineHeight: 1, // shadcn label.tsx: leading-none
          fontWeight: 500, // shadcn label.tsx: font-medium
          color: theme.vars.palette.text.primary, // shadcn label.tsx: ambient foreground (no color class)
          userSelect: "none", // shadcn label.tsx: select-none
        }),
      },
    },
    // -----------------------------------------------------------------------
    // Radio (RadioGroup item)
    //
    // Ground truth: apps/showcase/src/components/ui/radio-group.tsx
    // (radix-ui RadioGroup.Root/Item/Indicator, style "radix-nova"), read
    // directly and cross-checked with getComputedStyle() on the live shadcn
    // radio (light + dark; unchecked/checked/disabled;
    // hover/focus-visible on unchecked+checked) via the Playwright MCP -
    // same verification method as MuiCheckbox above.
    //
    // radio-group.tsx Item classes (RadioGroupPrimitive.Item, verbatim):
    //   group/radio-group-item peer relative flex aspect-square size-4
    //   shrink-0 rounded-full border border-input outline-none
    //   after:absolute after:-inset-x-3 after:-inset-y-2
    //   focus-visible:border-ring focus-visible:ring-3
    //   focus-visible:ring-ring/50 disabled:cursor-not-allowed
    //   disabled:opacity-50 aria-invalid:border-destructive
    //   aria-invalid:ring-3 aria-invalid:ring-destructive/20
    //   aria-invalid:aria-checked:border-primary dark:bg-input/30
    //   dark:aria-invalid:border-destructive/50
    //   dark:aria-invalid:ring-destructive/40 data-checked:border-primary
    //   data-checked:bg-primary data-checked:text-primary-foreground
    //   dark:data-checked:bg-primary
    // radio-group.tsx Indicator classes (RadioGroupPrimitive.Indicator,
    // verbatim): flex size-4 items-center justify-center
    // radio-group.tsx inner dot (a plain <span>, NOT a lucide icon - read
    // directly from the file rather than assumed per the task's own
    // warning; this file imports no icon library at all, unlike
    // checkbox.tsx's lucide CheckIcon):
    //   absolute top-1/2 left-1/2 size-2 -translate-x-1/2 -translate-y-1/2
    //   rounded-full bg-primary-foreground
    // No aria-invalid pair exists in this gallery (same out-of-scope
    // convention as MuiButton/MuiCheckbox above).
    //
    // Extracted class -> CSS:
    //   size-4                    -> width/height: 1rem (16px)
    //   aspect-square shrink-0    -> fixed 1rem square. The root itself
    //                                carries no items-center/justify-center
    //                                (unlike Checkbox's root) - centering the
    //                                dot is the separate Indicator element's
    //                                job (its own "flex items-center
    //                                justify-center" class). SwitchBase has
    //                                no extra indicator wrapper, so this is
    //                                reproduced on MUI's root instead - same
    //                                end-state pixels (an 8px dot centered in
    //                                a 16px circle), different owning
    //                                element.
    //   rounded-full              -> borderRadius: 50% (a true circle - NOT
    //                                the --radius scale, and NOT Checkbox's
    //                                flat 4px literal either; read fresh from
    //                                THIS file's own class, not copied from
    //                                Checkbox's rounded-[4px] by analogy)
    //   border border-input      -> border: 1px solid var(--input)
    //   outline-none              -> outline: none
    //   dark:bg-input/30          -> dark-only fill; light has NO background
    //                                class (same pattern as Checkbox -
    //                                confirmed via getComputedStyle: light
    //                                rest state backgroundColor is fully
    //                                transparent, "rgba(0, 0, 0, 0)")
    //   focus-visible:border-ring focus-visible:ring-3
    //   focus-visible:ring-ring/50
    //                             -> borderColor: ring, boxShadow: 0 0 0 3px
    //                                ring/50
    //   disabled:cursor-not-allowed disabled:opacity-50
    //                             -> opacity: 0.5, cursor: not-allowed (no
    //                                disabled:bg-* class, same as Checkbox)
    //   data-checked:border-primary data-checked:bg-primary
    //   data-checked:text-primary-foreground
    //                             -> checked-only: borderColor: primary,
    //                                backgroundColor: primary, color:
    //                                primary.contrastText. This text-color
    //                                class lives on the ROOT per this class
    //                                list (not the dot) - the dot's own
    //                                class is the separate, explicit
    //                                bg-primary-foreground below. The dot is
    //                                implemented here with backgroundColor:
    //                                "currentColor" so it resolves to the
    //                                identical contrastText value through the
    //                                root's own color inheritance, instead of
    //                                a second hardcoded token reference.
    //   dark:data-checked:bg-primary
    //                             -> re-asserts checked's primary background
    //                                over dark:bg-input/30's unconditional
    //                                fill - same trap/mechanism as
    //                                MuiCheckbox's own
    //                                dark:data-checked:bg-primary above
    //   size-2 (dot)              -> width/height: 0.5rem (8px)
    //   rounded-full (dot)        -> borderRadius: 50%
    //   bg-primary-foreground (dot) -> backgroundColor: currentColor (see
    //                                note directly above)
    //
    // GOTCHA - NO transition-colors class anywhere on Item (unlike
    // checkbox.tsx, which DOES carry transition-colors): confirmed by
    // reading this file's own class string, not copied from Checkbox's
    // block. State changes on the real shadcn radio are instant, not
    // animated - no `transition` is set below (left at the CSS initial
    // value). Restating Checkbox's 150ms transition here would be an
    // invented-by-analogy value the task's own rule explicitly forbids.
    //
    // GOTCHA - same disableRipple trap as MuiCheckbox above: MUI's
    // Radio.js destructures its OWN `disableRipple = false` default (via
    // `useDefaultProps({..., name: 'MuiRadio'})`) and forwards that
    // resolved (always-defined) value as an explicit prop down through
    // SwitchBase to ButtonBase, so the global
    // `MuiButtonBase.defaultProps.disableRipple: true` set above never
    // reaches it. Restated per-component below; verified with a REAL
    // Playwright mouse hover (not a synthetic dispatchEvent) that no grey
    // hover halo paints on hover or focus.
    //
    // GOTCHA - focus ring keys off `.Mui-focusVisible`, not `.Mui-focused`:
    // identical mechanism to MuiCheckbox above (Radio is SwitchBase/
    // ButtonBase family - the real focusable/hoverable element is the
    // absolutely-positioned, opacity:0 native `<input type="radio">`, and
    // ButtonBase's `handleFocus` reads `isFocusVisible(event.target)` off
    // that nested input via the bubbling focusin event, adding
    // `Mui-focusVisible` to the outer span even though the span itself is
    // never the literal focused DOM node).
    //
    // GOTCHA - MUI's own internal RadioRoot base style (Radio.js) sets
    // `color: text.secondary` unconditionally and, via its own `variants`
    // array (gated on `color: 'primary', disabled: false` - MUI Radio's own
    // default color, never overridden by this gallery),
    // `&.Mui-checked { color: primary.main }` and
    // `&.Mui-disabled { color: action.disabled }` - both at a specificity
    // this override's styleOverrides.root still beats by source order
    // (styleOverrides is always serialized after the component's own base
    // style + internal variants, same mechanism proven for
    // MuiButton/MuiCheckbox above). Not load-bearing for what actually
    // paints (the dot's color comes from this override's own
    // `&.Mui-checked` color, not MUI's default), but restated/neutralized
    // below anyway for hygiene, mirroring MuiCheckbox's equivalent note.
    //
    // `data-target` is placed on the internal `<input>` via
    // `slotProps={{ input: { "data-target": true } }}` for the standalone
    // pairs (mirrors MuiCheckbox exactly - see its own banner above for the
    // full z-index/hover-bubbling justification), and on the shadcn
    // RadioGroupItem root directly - radix RadioGroupItem renders a real
    // `<button type="button" role="radio">`, not a native input (confirmed
    // by reading @radix-ui/react-radio-group's compiled source), so the
    // rendered root IS the focusable/hoverable element on that side.
    // -----------------------------------------------------------------------
    MuiRadio: {
      defaultProps: {
        disableRipple: true, // see GOTCHA above - restated per-component, mirrors MuiCheckbox
        // shadcn: radio-group.tsx's Indicator renders a plain filled <span>
        // dot (size-2 rounded-full bg-primary-foreground), NOT a lucide
        // icon - read directly from the file rather than assumed (it
        // imports no icon library at all). `icon` (rendered while
        // unchecked) is the same dot made invisible via
        // `visibility: hidden` rather than omitted, for the same reason as
        // MuiCheckbox's `icon` above (SwitchBase always renders one of
        // `icon`/`checkedIcon`, and an invisible element paints zero pixels
        // - visually identical to shadcn's real DOM, which mounts no
        // Indicator at all when unchecked).
        icon: createElement("span", {
          "aria-hidden": true,
          style: {
            width: "0.5rem",
            height: "0.5rem",
            borderRadius: "50%",
            backgroundColor: "currentColor",
            visibility: "hidden" as const,
          },
        }),
        checkedIcon: createElement("span", {
          "aria-hidden": true,
          style: {
            width: "0.5rem",
            height: "0.5rem",
            borderRadius: "50%",
            backgroundColor: "currentColor",
          },
        }),
      },
      styleOverrides: {
        root: ({ theme }) => ({
          width: "1rem", // shadcn: size-4
          height: "1rem",
          padding: 0, // shadcn: no padding class (kills SwitchBaseRoot's own 9px base padding)
          boxSizing: "border-box",
          display: "flex", // centers the dot - see "aspect-square shrink-0" note above
          alignItems: "center",
          justifyContent: "center",
          flexShrink: 0, // shadcn: shrink-0
          borderRadius: "50%", // shadcn: rounded-full
          border: `1px solid ${theme.vars.palette.input}`, // shadcn: border border-input
          backgroundColor: "transparent", // shadcn: no base bg class (light)
          backgroundClip: "border-box", // shadcn: no bg-clip-padding class (left at CSS initial, same as Checkbox)
          color: theme.vars.palette.text.primary, // shadcn: ambient foreground (neutralizes MUI's own text.secondary - see GOTCHA above)
          outline: "none", // shadcn: outline-none
          cursor: "default", // shadcn: no cursor-pointer class; browser default (ButtonBase defaults to pointer)
          "&.Mui-checked": {
            borderColor: theme.vars.palette.primary.main, // shadcn: data-checked:border-primary
            backgroundColor: theme.vars.palette.primary.main, // shadcn: data-checked:bg-primary
            color: theme.vars.palette.primary.contrastText, // shadcn: data-checked:text-primary-foreground (dot inherits via currentColor)
          },
          "&.Mui-disabled": {
            opacity: 0.5, // shadcn: disabled:opacity-50
            cursor: "not-allowed", // shadcn: disabled:cursor-not-allowed
            color: theme.vars.palette.text.primary, // shadcn: no disabled color change - neutralizes MUI's own action.disabled tint
          },
          "&.Mui-focusVisible": {
            borderColor: theme.vars.palette.ring, // shadcn: focus-visible:border-ring
            boxShadow: `0 0 0 3px color-mix(in oklab, ${theme.vars.palette.ring} 50%, transparent)`, // shadcn: focus-visible:ring-3 ring-ring/50
          },
          ...theme.applyStyles("dark", {
            backgroundColor: `color-mix(in oklab, ${theme.vars.palette.input} 30%, transparent)`, // shadcn: dark:bg-input/30
            "&.Mui-checked": {
              backgroundColor: theme.vars.palette.primary.main, // shadcn: dark:data-checked:bg-primary (re-assert over dark:bg-input/30)
            },
          }),
        }),
      },
    },
    // -----------------------------------------------------------------------
    // RadioGroup (container)
    //
    // Ground truth: apps/showcase/src/components/ui/radio-group.tsx's Root
    // classes (RadioGroupPrimitive.Root, verbatim): "grid w-full gap-2".
    // MUI's <RadioGroup> renders @mui/material/FormGroup under the hood
    // (confirmed by reading RadioGroup.js: it wraps children in a plain
    // `<FormGroup role="radiogroup">`) - themed here via MuiFormGroup rather
    // than a RadioGroup-specific slot, since RadioGroup ships no
    // styleOverrides entry of its own to hang this on. No other component in
    // this app's gallery renders FormGroup yet, so this addition is scoped
    // cleanly to this task.
    //
    // Extracted class -> CSS:
    //   grid                      -> single-column auto-flow grid == a
    //                                vertical stack (no explicit
    //                                grid-template-columns is set, so every
    //                                child occupies its own row) - reproduced
    //                                as FormGroup's own existing
    //                                flexDirection: column (left unchanged)
    //                                rather than actually switching display
    //                                to grid: the rendered layout is
    //                                pixel-identical for a single column of
    //                                block-level rows, and changing `display`
    //                                risks fighting FormGroup's own `row`
    //                                variant machinery for no visual gain.
    //   w-full                    -> width: 100% (needed so both sides
    //                                resolve to the identical box width
    //                                inside the gallery's centered cell -
    //                                without this, MUI's FormGroup would stay
    //                                content-sized while shadcn's RadioGroup
    //                                stretches to the cell, so the two would
    //                                center at different horizontal offsets)
    //   gap-2                     -> gap: 0.5rem (8px) between rows
    // -----------------------------------------------------------------------
    MuiFormGroup: {
      styleOverrides: {
        root: {
          width: "100%", // shadcn: w-full
          gap: "0.5rem", // shadcn: gap-2
        },
      },
    },
    // Per-component overrides are appended by later tasks, one banner each.
  },
})
